# Header
menu:
  主页: /
  所有文章: /archives
  技术之美: /technology
  产品之道: /product
  生活杂谈: /life

# SubNav
subnav:
  github: "https://github.com/xyyh"
  weibo: "http://weibo.com/u/5346438017/home?wvr=5&lf=reg"
  #mail: "#"
  zhihu: "https://www.zhihu.com/people/cang-ling-yang-30"
  #rss: "/atom.xml"
  #douban: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

#rss: /atom.xml

# Content
excerpt_link: 阅读全文
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /img/favicon.ico

#你的头像url
avatar: /img/xyyh_head.png
#是否开启分享
share_jia: true
share_addthis: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: xxxx
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  xyb的博客: http://xybcoder.github.io/
  舞影凌风: http://www.apkfuns.com/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme:
  家乡: 江西抚州
  学校: 华东交通大学
  职业: 爱幻想的程序员
  爱好: 放空自己，行走各地
